android {
    flavorDimensions += "flavor-type"

    productFlavors {
        prod {
            dimension "flavor-type"
            applicationId "com.dateu.prod.doitdoit"
            resValue "string", "app_name", "두잇두잇"
        }
        dev {
            dimension "flavor-type"
            applicationId "com.dateu.dev.doitdoit"
            resValue "string", "app_name", "[DEV]두잇두잇"
        }
    }
}